version: '3.3'
services:
  javaEcommerce:
    container_name: hellobank-ibm
    image: IMG_PARA_SUBSTITUIR
    environment:
      MYSQL_HOST: hellobank-rds.c0jzwg6p99gu.us-east-1.rds.amazonaws.com
      DATABASE: hellobank
      MYSQL_USER: root
      MYSQL_PASS: a2b3c4d5
    ports:
      - "8090:8080"
